<%
std_opts = "--verbose --expand --format html --out=./log/log.html --format junit --out=./log --format pretty features --tags ~@wip --tags ~@bug"
%>
default: -r features <%= std_opts %> --tags ~@demo features